pipeline {
    agent any 

    stages {
        stage('check') {
            steps {
                echo "checking your code"
                
               
            }
        }

        stage('docker build') {
            steps {
                echo "building dockerfile"
                sh "docker build -t aliashmawy/day2:${env.BUILD_NUMBER} day2/task3"
                 
            }
        }
        
        stage('docker push') {  
            steps {
                echo "docker push is running now"
                withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "echo $PASSWORD | docker login -u $USERNAME --password-stdin"
                    sh "docker push aliashmawy/day2:${env.BUILD_NUMBER}"
                    
                }
            }
        }    
    }

}