pipeline {
    agent any

    environment {
        
        BASTION_HOST = "ubuntu@3.88.50.28"
        PRIVATE_HOST = "ubuntu@172.31.150.22"
        SSH_KEY = credentials('vockey1')
        SCRIPT_FILE_ID = 'task9_script'
    }

    stages {
        stage('Prepare Script') {
        steps {
            configFileProvider([configFile(fileId: "${SCRIPT_FILE_ID}", targetLocation: 'script.sh')]) {
                sh 'chmod +x script.sh'
            }
        }
    }
        stage('Run Script on Private EC2') {
            steps {
                script {
                    def command = """
                        pwd
                        ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no ${BASTION_HOST} \\
                        ssh -o StrictHostKeyChecking=no ${PRIVATE_HOST} 'bash -s' < script.sh
                    """
                    sh command
                }
            }
        }
    }
}
