pipeline {
    agent any


    stages {
        stage('Print Parameters') {
            steps {
                echo "Deploying to: ${params.DEPLOY_ENV}"
                echo "Debug mode: ${params.ENABLE_DEBUG}"
                echo "Region: ${params.REGION}"
            }
        }
    }
}
