apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    tier: front-end
    app: nginx
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: httpd:2.4-alpine
  replicas: 2
  selector:
    matchLabels:
      app: myapp