pipeline {
    agent any

    environment {
        KUBECONFIG = "/var/jenkins_home/.kube/config"  // use the kubeconfig in the repo
    }

    stages {
        stage('Show kubeconfig info') {
            steps {
                sh 'kubectl config get-contexts'
            }
        }

        stage('Apply Deployment and Service') {
            steps {
                sh '''
                    kubectl apply -f day3/task1/deployments.yaml
                    kubectl apply -f day3/task1/NodePort.yaml
                '''
            }
        }
    }
}
