pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('access_key')
        AWS_SECRET_ACCESS_KEY = credentials('secret_key') 
    }

    stages {

        stage('Terraform Init') {
            steps {
                dir('day2/task8'){
                    sh 'terraform init'
                }
               
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('day2/task8'){
                sh 'terraform apply -auto-approve'
            }
        }
    }
}
}