pipeline {
    agent any

    environment {
        TF_VAR_aws_access_key = credentials('access_key')
        TF_VAR_aws_secret_key = credentials('secret_key') 
    }

    stages {
        stage('List Files') {
    steps {
        sh 'ls -la'
        }
        }

        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'terraform apply -auto-approve'
            }
        }
    }
}
