pipeline {
    agent any

    environment {
        TF_VAR_aws_access_key = credentials('access_key')
        TF_VAR_aws_secret_key = credentials('secret_key') 
    }

    stages {

        stage('Terraform Init') {
            steps {
                dir('day2/task8'){
                    sh 'terraform init'
                }
               
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('day2/task8'){
                sh 'terraform apply -auto-approve'
            }
        }
    }
}
